using System;

namespace SheetReader
{
    public class BookDocumentColumn
    {
        public BookDocumentColumn(Column column)
        {
            ArgumentNullException.ThrowIfNull(column);
            Column = column;
        }

        public Column Column { get; }
        public virtual int Index => Column.Index;
        public virtual string? Name => Column.Name;
        public virtual bool IsAutoGenerated { get; set; }

        public override string ToString() => Column.Name ?? string.Empty;
    }
}
